### ISSUE TITLE
.meta file encoding 

### ISSUE THREAD

**Issue by kaakaa** [kaakaa/ppt-batch#2]
When .meta file is shift_jis encoding, occur bellow exception.

```
upload error: D:\ppt-batch-0.0.3\.\uploads\56fdefdde21b840009ae7675                                 
javax.script.ScriptException: TypeError: Cannot call undefined in <eval> at line number 1                                  
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)              
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)                            
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)                            
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)                            
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)                                
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)                                           
        at org.kaakaa.pptmuseum.batch.resources.MetaFileParser.parse(MetaFileParser.java:20)                               
        at org.kaakaa.pptmuseum.batch.resources.SlideResource.makeRequestBody(SlideResource.java:25)                       
        at org.kaakaa.pptmuseum.batch.HttpClient.upload(HttpClient.java:26)                                                
        at org.kaakaa.pptmuseum.batch.Batch.lambda$exec$0(Batch.java:28)                                                   
        at org.kaakaa.pptmuseum.batch.Batch$$Lambda$3/2513828.accept(Unknown Source)                                       
        at java.util.Iterator.forEachRemaining(Iterator.java:116)                                                          
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)                             
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)                                     
        at org.kaakaa.pptmuseum.batch.Batch.exec(Batch.java:26)                                                            
        at org.kaakaa.pptmuseum.batch.Main.main(Main.java:33)                                                              
Caused by: <eval>:1 TypeError: Cannot call undefined                                                                       
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)                                               
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)                                          
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)                                          
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)                                          
        at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)                                      
        at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)                                               
        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:102)                  
        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:94)                   
        at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGua
rdingDynamicLinker.java:176)                                                                                               
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker
.java:124)                                                                                                                 
        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)              
        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)                                              
        at jdk.nashorn.internal.scripts.Script$17$\^eval\_.:program(<eval>:1)                                              
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:636)                             
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)                                     
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)                                        
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:437)                            
        ... 14 more                                                                                                        
```

**Comment by kaakaa** [comment]
This error occurs on Java 1.8.0_51 environment.

ppt-batch use `Java.asJSONCompatible(obj)` for Nashorn.
But `Java.asJOSNCompatible(obj)` was added on Java 1.8.0_60.

[Java™ SE Development Kit 8, Update 60 Release Notes](http://www.oracle.com/technetwork/java/javase/8u60-relnotes-2620227.html)

I write caution about requirements for jre version in README.md.
